# Отчет по лабораторной работе №3"NumPy"
## Выполнила студентка группы T12О-101М-20
## "Управление продуктовой разработкой it сервисов"

### Давыдова Елизавета
#### 07.11.2020

In [2]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [13]:
v = np.array([1,2,3,4,5])
z = np.zeros((len(v)-1)*3 + len(v))
print(z)
z[::4] = v
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице

In [22]:
A = np.arange(8).reshape(4,2)
print(A)
A[[1,2]] = A[[2,1]]
print(A)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [4 5]
 [2 3]
 [6 7]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники


In [44]:
set_of_points = np.random.randint(0,30,(10,3))
a = np.roll(set_of_points.repeat(2,axis=1),-1,axis=1)
a = a.reshape(len(a)*3,2)
a = np.sort(a,axis=1)
b = a.view( dtype=[('p0',a.dtype),('p1',a.dtype)] )
b = np.unique(b)
print(b)

[( 0,  1) ( 0, 16) ( 0, 19) ( 0, 23) ( 1, 16) ( 4,  6) ( 4, 28) ( 5, 16)
 ( 5, 21) ( 6,  6) ( 6, 27) ( 6, 28) ( 8, 13) ( 8, 25) ( 8, 27) (10, 13)
 (10, 22) (13, 22) (13, 25) (14, 17) (14, 18) (14, 20) (14, 24) (16, 21)
 (17, 20) (18, 24) (19, 23) (25, 27)]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [52]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(6), 3)
print(Z)
print(np.arange(6))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]
[0 1 2 3 4 5]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [60]:
a = np.random.randint(0,2,30)
print(a)
np.logical_not(a, out=a)
print(a)

b = np.random.randint(-1,2,10)
print(b)
np.negative(b, out=b)
print(b)

[0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 1 0 0]
[1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1 1]
[-1 -1  0  1  0  0  0  0  0  1]
[ 1  1  0 -1  0  0  0  0  0 -1]


Посчитать ранг матрицы


In [64]:
a = np.arange(8).reshape(4,2)
print(a)
print(np.linalg.matrix_rank(Z))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
2


Найти наиболее частое значение в массиве

In [71]:
a = np.random.randint(0,5,30)
print(a)
k = np.bincount(a)
print(k)
print(k.argmax())

[0 4 2 4 1 2 0 0 4 2 1 4 4 3 4 3 1 3 0 4 2 1 0 4 1 0 4 1 2 1]
[6 7 5 3 9]
4


Извлечь все смежные 3x3 блоки из 10x10 матрицы


In [12]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 3 3]
   [3 3 1]
   [2 3 3]]

  [[3 3 1]
   [3 1 0]
   [3 3 0]]

  [[3 1 0]
   [1 0 2]
   [3 0 1]]

  [[1 0 1]
   [0 2 1]
   [0 1 4]]

  [[0 1 4]
   [2 1 4]
   [1 4 1]]

  [[1 4 1]
   [1 4 4]
   [4 1 2]]

  [[4 1 3]
   [4 4 2]
   [1 2 0]]

  [[1 3 4]
   [4 2 2]
   [2 0 2]]]


 [[[3 3 1]
   [2 3 3]
   [0 4 4]]

  [[3 1 0]
   [3 3 0]
   [4 4 4]]

  [[1 0 2]
   [3 0 1]
   [4 4 3]]

  [[0 2 1]
   [0 1 4]
   [4 3 3]]

  [[2 1 4]
   [1 4 1]
   [3 3 2]]

  [[1 4 4]
   [4 1 2]
   [3 2 2]]

  [[4 4 2]
   [1 2 0]
   [2 2 3]]

  [[4 2 2]
   [2 0 2]
   [2 3 2]]]


 [[[2 3 3]
   [0 4 4]
   [3 2 3]]

  [[3 3 0]
   [4 4 4]
   [2 3 0]]

  [[3 0 1]
   [4 4 3]
   [3 0 3]]

  [[0 1 4]
   [4 3 3]
   [0 3 4]]

  [[1 4 1]
   [3 3 2]
   [3 4 4]]

  [[4 1 2]
   [3 2 2]
   [4 4 0]]

  [[1 2 0]
   [2 2 3]
   [4 0 3]]

  [[2 0 2]
   [2 3 2]
   [0 3 1]]]


 [[[0 4 4]
   [3 2 3]
   [3 2 3]]

  [[4 4 4]
   [2 3 0]
   [2 3 2]]

  [[4 4 3]
   [3 0 3]
   [3 2 4]]

  [[4 3 3]
   [0 3 4]
   [2 4 3]]

  [[3 3 2]
   

Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [72]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Дан массив 16x16, посчитать сумму по блокам 4x4

In [76]:
a = np.ones((16,16))
n = 4
S = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], n), axis=0),
                                       np.arange(0, a.shape[1], n), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


Найти n наибольших значений в массиве


In [89]:
a = np.arange(10)
np.random.shuffle(a)
n = 5
print(a[np.argpartition(-a,n)[:n]])

[8 9 7 6 5]


Построить прямое произведение массивов (все комбинации с каждым элементом)


In [17]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [18]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4 5 6 7]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])


In [19]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 4 1]
 [3 0 2]
 [0 1 1]
 [2 2 2]
 [4 2 3]
 [2 3 2]
 [2 3 1]
 [0 1 3]
 [3 3 3]
 [1 3 4]]
[[2 4 1]
 [3 0 2]
 [0 1 1]
 [4 2 3]
 [2 3 2]
 [2 3 1]
 [0 1 3]
 [1 3 4]]


Преобразовать вектор чисел в матрицу бинарных представлений

In [20]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Дан двумерный массив. Найти все различные строки


In [21]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [110]:
a = np.arange(5)
b = np.arange(5)
print(np.einsum('i->', a))            # np.sum(A)
print(np.einsum('i,i->i', a, b))    # A * B
print(np.einsum('i,i', a, b))   # np.inner(A, B)
print(np.einsum('i,j', np.arange(2)+1, b))      # np.outer(A, B)

10
[ 0  1  4  9 16]
30
[[0 1 2 3 4]
 [0 2 4 6 8]]
